version: '3'

networks:
  smplct_view_network:

services:
  postgres:
    # TypeORM fails with Postgres v.12
    image: postgres:11.5
    ports:
      - 5454:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: smplct_view_app
    volumes:
      - ./.db-data:/var/lib/postgresql/data
    networks:
      - smplct_view_network
  redis:
    image: redis:alpine
    ports:
      - 6399:6379
    command: redis-server
    networks:
      - smplct_view_network
