version: '3'

networks:
  smplct_view_network:

services:
  eventstore.db-viewapp:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_MEM_DB=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - eventstore-volume-data:/var/lib/eventstore
      - eventstore-volume-logs:/var/log/eventstore
  postgres-viewapp:
    # TypeORM fails with Postgres v.12
    image: postgres:11.10
    container_name: smplct_view_psql
    ports:
      - 5454:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: smplct_view_app
    volumes:
      - ./.db-data:/var/lib/postgresql/data
    networks:
      - smplct_view_network
  redis-viewapp:
    image: redis:alpine
    container_name: smplct_view_redis
    ports:
      - 6399:6379
    command: redis-server
    networks:
      - smplct_view_network
  nginx-viewapp:
    privileged: true
    userns_mode: host
    image: jwilder/nginx-proxy
    container_name: nginx-viewapp
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - smplct_view_network
volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
