version: '3'

networks:
  nestjsx_crud:

services:
  postgres:
    # TypeORM fails with Postgres v.12
    image: postgres:11.5
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: email_admin
    volumes:
      - ./.db-data:/var/lib/postgresql/data
    networks:
      - nestjsx_crud
  redis:
    image: redis:alpine
    ports:
      - 6399:6379
    command: redis-server
    networks:
      - nestjsx_crud
